config/routes.rb
Rails.application.routes.draw do
  resources :usercontacts
  devise_for :users
	resources :posts do
		resources :comments
	end



	root "posts#index"

	get '/about', to: 'pages#about'  #how to create a static page 
	get '/summerprograms', to: 'pages#summerprograms'
	get '/collegebound', to: 'pages#collegebound'
	get '/edtools', to: 'pages#edtools'
	get '/collegeresearchtools', to: 'pages#collegeresearchtools'
	get '/planningtools', to: 'pages#planningtools'
	

	match '/contacts',     to: 'contacts#new',             via: 'get'
	resources "contacts", only: [:new, :create]

	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contacts.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true

end

app/models/uniprograms.rb
class Uniprogram < ApplicationRecord
	
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usercontact.rb
class Usercontact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment =@post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
		
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
		  flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
		else
		  flash.now[:error] = 'Cannot send message.'
		  render :new
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end

	def summerprograms
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to post_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/user_ms_controller.rb
class UserMsController < ApplicationController
  before_action :set_user_m, only: [:show, :edit, :update, :destroy]

  def create
    @user_m = UserM.new(user_m_params)

    respond_to do |format|
      if @user_m.save
        format.html { redirect_to @user_m, notice: 'User m was successfully created.' }
        format.json { render :show, status: :created, location: @user_m }
      else
        format.html { render :new }
        format.json { render json: @user_m.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_ms/1
  # PATCH/PUT /user_ms/1.json
  def update
    respond_to do |format|
      if @user_m.update(user_m_params)
        format.html { redirect_to @user_m, notice: 'User m was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_m }
      else
        format.html { render :edit }
        format.json { render json: @user_m.errors, status: :unprocessable_entity }
      end
    end
  end

  
  private
    # Use callbacks to share common setup or constraints betw een actions.
    def set_user_m
      @user_m = UserM.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_m_params
      params.require(:user_m).permit(:name, :email, :login)
    end
end

app/controllers/usercontacts_controller.rb
class UsercontactsController < ApplicationController
  before_action :set_usercontact, only: [:show, :edit, :update, :destroy]

  # GET /usercontacts
  # GET /usercontacts.json
  def index
    @usercontacts = Usercontact.all
  end

  # GET /usercontacts/1
  # GET /usercontacts/1.json
  def show
  end

  # GET /usercontacts/new
  def new
    @usercontact = Usercontact.new
  end

  # GET /usercontacts/1/edit
  def edit
  end

  # POST /usercontacts
  # POST /usercontacts.json
  def create
    @usercontact = Usercontact.new(usercontact_params)

    respond_to do |format|
      if @usercontact.save
        format.html { redirect_to @usercontact, notice: 'Usercontact was successfully created.' }
        format.json { render :show, status: :created, location: @usercontact }
      else
        format.html { render :new }
        format.json { render json: @usercontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usercontacts/1
  # PATCH/PUT /usercontacts/1.json
  def update
    respond_to do |format|
      if @usercontact.update(usercontact_params)
        format.html { redirect_to @usercontact, notice: 'Usercontact was successfully updated.' }
        format.json { render :show, status: :ok, location: @usercontact }
      else
        format.html { render :edit }
        format.json { render json: @usercontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usercontacts/1
  # DELETE /usercontacts/1.json
  def destroy
    @usercontact.destroy
    respond_to do |format|
      format.html { redirect_to usercontacts_url, notice: 'Usercontact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usercontact
      @usercontact = Usercontact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usercontact_params
      params.require(:usercontact).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/uniprograms_helper.rb
module UniprogramsHelper
end

app/helpers/usercontacts_helper.rb
module UsercontactsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body "> <%= comment.body %> </p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago </p>
	</div>

	<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.post, comment],
					method: :delete,
					class: "button",
					data: { confirm: 'Are you sure?' } %>
		</p>
 	<% end %>
</div>	

app/views/comments/_form.html.erb
<div id="content-wrapper">

	<div class="site">

		<%= form_for([@post, @post.comments.build]) do |f| %>

	
			<div class="col-lg-10 col-sm-8">

				<div class="form-group">  
				
				  <%= f.text_area :body, class: "form-control" %>
				</div>

				
				<div class="form-group">
				  <%= f.submit "Submit Comment", class: "btn btn-primary" %>
				</div>   
			</div>		
				
			
		<% end %>
	</div>
</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div class="errors">
			<h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li> <%= msg %> </li>

				<% end %>
			</ul>
		</div>

	<% end %>

	<div class="container">
		<div class="row">
			<div class="col-lg-10 col-sm-10 col-sm-offset-2">
				<div class="panel panel-default">
				<div class="panel-heading">
				  <h2 class="question-new-item">New Post</h2>
				</div>
	        	<div class="panel-body">
				
					<div class="form-group">  
					  <%= f.label :title, "Title" %> 
					  <%= f.text_field :title, class: "form-control" %>
					</div>

					<div class="form-group">  
					  <%= f.label :body %>
					  <%= f.text_area :body, 
					                    class: "form-control" %>
					</div>

					
					<div class="form-group">
					  <%= f.submit "Submit", class: "btn btn-primary" %>
					</div>   
				</div>
			</div>
		</div>
	</div>

<% end %> 

app/views/posts/edit.html.erb
<div class="post_wrapper">
	<h1> Edit post </h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div id="content-wrapper">

	<div class="site">
		<% @posts.each do |post| %>


			<div class="card card-outline-primary col-md-6 col-sm-6">
				<div class="card-block ">
					<blockquote class="card-blockquote">
						<h2 class="title"> <%= link_to post.title, post %></h2>

						<p class="date"> <%= post.created_at.strftime("%B, %d, %Y") %></p>
					</blockquote>
				</div>
			</div>
				
			


		<% end %>
	</div>


</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-2">
			<div class="panel panel-default">
			<div class="panel-heading">
			  <h2 class="question-new-item">New Post</h2>
			</div>
        	<div class="panel-body">

				<%= form_for(@post) do |f| %>
					<div class="form-group">  
					  <%= f.label :title, "Headline" %> 
					  <%= f.text_field :title, placeholder: "What is the title of your post", class: "form-control" %>
					</div>

					<div class="form-group">  
					  <%= f.label :body %>
					  <%= f.text_area :body, 
					                    placeholder: "Express yourself",
					                    class: "form-control" %>
					</div>

					
					<div class="form-group">
					  <%= f.submit "Submit question", class: "btn btn-primary" %>
					</div>    
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div id="content-wrapper">

	<div class="site">
		<div class="col-lg-10 ">
			
			<h1 class="title "><%= @post.title %></h1>

			<p class="date">
				Posted <%= time_ago_in_words(@post.created_at) %> Ago
				<% if user_signed_in? %>
					| <%= link_to 'Edit', edit_post_path(@post) %>
					| <%= link_to 'Delete', post_path(@post), method: :delete, data:{ confirm: 'Are you sure?'} %>
				<% end %>	
			</p>

			<p class="showpost-content"><%= @post.body %></p>
			<hr>

			<div id="comments">
				<h3 class="lead"><%= @post.comments.count %> Comments</h3>
				<%= render @post.comments %>

				<h4 class="lead">Leave a comment:</h4>
				<%= render "comments/form" %>
			</div>
		

		</div>
	</div>


</div>

app/views/usercontacts/_form.html.erb
<%= form_for(usercontact) do |f| %>
  <% if usercontact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usercontact.errors.count, "error") %> prohibited this usercontact from being saved:</h2>

      <ul>
      <% usercontact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usercontacts/edit.html.erb
<h1>Editing Usercontact</h1>

<%= render 'form', usercontact: @usercontact %>

<%= link_to 'Show', @usercontact %> |
<%= link_to 'Back', usercontacts_path %>

app/views/usercontacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usercontacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usercontacts.each do |usercontact| %>
      <tr>
        <td><%= usercontact.name %></td>
        <td><%= usercontact.email %></td>
        <td><%= usercontact.login %></td>
        <td><%= link_to 'Show', usercontact %></td>
        <td><%= link_to 'Edit', edit_usercontact_path(usercontact) %></td>
        <td><%= link_to 'Destroy', usercontact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usercontact', new_usercontact_path %>

app/views/usercontacts/new.html.erb
<h1>New Usercontact</h1>

<%= render 'form', usercontact: @usercontact %>

<%= link_to 'Back', usercontacts_path %>

app/views/usercontacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @usercontact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usercontact.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @usercontact.login %>
</p>

<%= link_to 'Edit', edit_usercontact_path(@usercontact) %> |
<%= link_to 'Back', usercontacts_path %>