config/routes.rb
Rails.application.routes.draw do
  resources :usercontacts
  devise_for :users
	resources :posts do
		resources :comments
	end



	root "posts#index"

	get '/about', to: 'pages#about'  #how to create a static page 
	get '/summerprograms', to: 'pages#summerprograms'
	get '/collegebound', to: 'pages#collegebound'
	get '/edtools', to: 'pages#edtools'
	get '/collegeresearchtools', to: 'pages#collegeresearchtools'
	get '/planningtools', to: 'pages#planningtools'
	

	match '/contacts',     to: 'contacts#new',             via: 'get'
	resources "contacts", only: [:new, :create]

	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contacts.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true

end

app/models/uniprograms.rb
class Uniprogram < ApplicationRecord
	
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usercontact.rb
class Usercontact < ApplicationRecord
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment =@post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
		
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
		  flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
		else
		  flash.now[:error] = 'Cannot send message.'
		  render :new
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end

	def summerprograms
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to post_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/user_ms_controller.rb
class UserMsController < ApplicationController
  before_action :set_user_m, only: [:show, :edit, :update, :destroy]

  def create
    @user_m = UserM.new(user_m_params)

    respond_to do |format|
      if @user_m.save
        format.html { redirect_to @user_m, notice: 'User m was successfully created.' }
        format.json { render :show, status: :created, location: @user_m }
      else
        format.html { render :new }
        format.json { render json: @user_m.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_ms/1
  # PATCH/PUT /user_ms/1.json
  def update
    respond_to do |format|
      if @user_m.update(user_m_params)
        format.html { redirect_to @user_m, notice: 'User m was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_m }
      else
        format.html { render :edit }
        format.json { render json: @user_m.errors, status: :unprocessable_entity }
      end
    end
  end

  
  private
    # Use callbacks to share common setup or constraints betw een actions.
    def set_user_m
      @user_m = UserM.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_m_params
      params.require(:user_m).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/uniprograms_helper.rb
module UniprogramsHelper
end

app/helpers/usercontacts_helper.rb
module UsercontactsHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="site">
    <div class="footer-above">
        <div class="">
            <div class="row">
                <div class="footer-col text-center col-md-4">
                    <h3>Location</h3>
                    <p>3481 Melrose Place
                        <br>Beverly Hills, CA 90210</p>
                </div>
                <div class="footer-col text-center col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
             	           </li>
                    </ul>
                </div>
                <div class="footer-col text-center col-md-4">
                    <h3>About Freelancer</h3>
                    <p>Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="site">
            <div class="row">
                <div class="col-lg-12 text-center">
                    Copyright &copy; Your Website 2016
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= favicon_link_tag 'favicon.ico' %>
	<%= csrf_meta_tags %>


	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Simple Sidebar - Start Bootstrap Template</title>

	

</head>
<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">Mongoose Labs</a>
                </li>
				<!--<li><%= link_to "Blog", root_path %></li> -->
				<li><%= link_to "About", about_path %></li>  <!--how to link to pages -->
				<li><%= link_to "Summer programs", summerprograms_path %></li>
				<li><%= link_to "Educational Tools", edtools_path %></li>
				<li><%= link_to "College Research Tools", collegeresearchtools_path %></li>
				<li><%= link_to "College Bound Programs", collegebound_path %></li>
				<li><%= link_to "College Planning Tools", planningtools_path %></li>

				<!--<% if user_signed_in? %>
					<div class="buttons">
						<button class="button"><%= link_to "New Post", new_post_path %></button>
						<button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
					</div>
					
				<% end %> 

				Undo this when I want to create a blog post!!!!
	        </ul>
	        <div>
	        	<% if !user_signed_in? %>
					<p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
				<% end %>
	        </div>
	            -->
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-4">
                        <a href="#menu-toggle" class="button main-menu" id="menu-toggle">Menu</a>
                    </div>

                    <div class="col-xs-4">
						<% if current_page?(root_path) %>
							<p>All Posts</p>
						<% elsif current_page?(about_path) %> <br>
							
						<% else %>
							<%= link_to "Back to All Posts", root_path %>
						<% end %>

						
					</div>

					<% flash.each do |name, msg| %>
						<%= content_tag(:div, msg, class: "alert") %>
					<% end %>

					<%= yield %>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

        <%= render 'layouts/footer' %>
        <div class="site">
      		
      		
      	</div>
        
    </div>

        <!-- Footer -->


    <div id="content-wrapper">

		
    </div>


        <!-- #footer-->

    
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

app/views/pages/about.html.erb
<div id="content-wrapper">
	<div class="site">
		<h1> I need to add a edit profile feature</h1>

		<div>
			<h2 class="lead"><q>Education should be a right, not a privilege. 
			Every person in this country who has the desire and ability should be able to get all the education they need regardless of the income of their family. 
			</q> </h2> 
			<cite class="text-right">Bernie Sanders</cite> <hr >
		</div>
		
		<div class="">
			<p>The internet is vast with information to prepare students for college, from college bound initiative programs to online tools for self-preparation. As Mongoose labs plans to dismantle the pipeline from school to prison, our first course of action is to disseminate carefully curtailed lists of resources for high schools students to utilize. There are many great opportunities for high school students and we here at Mongoose Labs want to ensure they are displayed. 
			</p>
			<p>Each program or tool we have listed on this site has been verified as an advocate of educational equality. </p>
		</div>
	</div>
</div>

app/views/pages/collegebound.html.erb
<div id="content-wrapper">

	<div class="site">
		<h1 class="col-sm-12 lead site-content"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</h1>


		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="http://www.ywln.org/college-prep">YWLN - Young Women's Leadership Network - CollegeBound Initiative</a></h3> <br>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>

		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="https://www.girlswritenow.org/what-we-do/programs/get-to-college/">College Bound Program - Girls Write Now	</a></h3> <br>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>

		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="https://www.collegegreenlight.com/cboProfile/collegebound-initiative">CBO Profile: CollegeBound Initiative | College Greenlight	</a></h3> <br>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>

		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="http://www.ywcanyc.org/programs/high-school-programs/">High School and College Bound Initiatives YWCA of the City of New York</a></h3> <br>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>

		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="http://www.childrenofthecity.org/college-bound/">College Bound | Children of the City	</a></h3> <br>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>

		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="http://urbanwordnyc.org/creatively-college-bound/">Creatively College Bound – Urban Word NYC</a></h3>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		</div>
		
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="https://legaloutreach.org/?page_id=144">College Bound | Legal Outreach</a></h3>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="https://www.bottomline.org/">Bottom Line</a></h3>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="http://americaneedsyou.org/">America Needs You</a></h3>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="https://www.insidehighered.com/blogs/gradhacker">Grad Hacker	</a></h3>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		</div>
		
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="http://collegebound.org/">College Bound - Academic enrichment and resources to prepare for</a></h3>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href=""></a></h3>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href="http://www.pathwaystocollege.org/">Pathways to College	</a></h3>
			<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
		</div>
		<div class="col-sm-12 site-content">
			<h3><a target="_blank" href=""></a></h3>
		</div>
	</div>
	

</div>

app/views/pages/collegeresearchtools.html.erb
<div id="content-wrapper">

	<div class="site">

		<div class="col-sm-12">
			<h1 class="lead">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</h1>
		</div>
		


		<h2 class="lead"></h2>

		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="http://www.cappex.com/">Cappex</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="http://www.collegemajors101.com/">CollegeMajors101</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
			
		</div>
		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="http://www.collegeboard.com/">College Board</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
		</div>
		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="startclass.com">StartClass</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
			
		</div>
		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="https://www.niche.com/?ref=colleges">College Niche</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
		</div>
		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="http://apply101.com">Apply101</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
		</div>
	</div>

	<div class="site">

		<div class="col-sm-12">
			<h2> Financial assistance tools</h2>
		</div>
		
		
		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="https://collegeabacus.com/">College Abacus</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
		</div>
		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="https://bigfuture.collegeboard.org/pay-for-college/tools-calculators">Financial Aid Tools - The College Board</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
		</div>
		<div class="col-lg-4 site-content">

			<h3><a target="_blank" href="http://colleges.startclass.com/stories/5672/most-financial-aid">College StartClass</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
		</div>

	</div>
</div>


	
	
	

	

app/views/pages/edtools.html.erb
<div id="content-wrapper">

	<div class="site">
		<div class="col-sm-12 site-content">
			<h1 class="lead">Add Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.   </h1>
		</div>
		


		<h2 class="lead col-sm-12 site-content">Free Online SAT/ACT Prep</h2>


		<div class="col-lg-6 col-sm-12 site-content site-content">

			<h3><a target="_blank" href="http://prep4sat.com/">Prep4SAT</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
		<div class="col-lg-6 col-sm-12 site-content">

			<h3><a target="_blank" href="https://www.prepfactory.com/">PrepFactory.com </a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
		<div class="col-lg-6 col-sm-12 site-content">

			<h3><a target="_blank" href="https://www.khanacademy.org/sat">Official SAT® Practice | Khan Academy </a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
	


		<h2 class="lead col-sm-12 site-content">Free Online Courses</h2>

		<div class="col-lg-6 col-sm-12 site-content">

			<h3><a target="_blank" href="https://www.khanacademy.org/">Khan Academy</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
		<div class="col-lg-6 col-sm-12 site-content">

			<h3><a target="_blank" href="https://www.coursera.org/">Coursera | Online Courses From Top Universities </a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
		<div class="col-lg-6 col-sm-12 site-content">

			<h3><a target="_blank" href="https://www.edx.org/">edX | Free online courses from the world's best universities</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
		<div class="col-lg-6 col-sm-12 site-content">

			<h3><a target="_blank" href="https://ocw.mit.edu/">MIT OpenCourseWare | Free Online Course Materials</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
		<div class="col-lg-6 col-sm-12 site-content">

			<h3><a target="_blank" href="https://www.class-central.com/">Class Central</a></h3>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>

		</div>
	</div>


</div>


	

app/views/pages/summerprograms.html.erb
<div id="content-wrapper">

	<div class="site">

		<h3 class="lead">
			Text about summer programs and the benefits.... <br>
			The link below has over 100 summer programs around the country <br>
			make the link open a new tab
		</h3>


		<h2><a target="_blank" href="http://blog.prepscholar.com/pre-college-summer-programs-for-high-school-students">128 Pre-College Summer Programs for High School Students</a></h2>

		<h2><a target="_blank" href="http://schools.nyc.gov/ui/cms/sites/empoweringboys/docs/takeaction/Real_World/High%20School%20Internships%20and%20Scholarships.pdf">Opporunities</a></h2>

	</div>

</div>